import { PageHeaderContent } from '../../shared/models/page-header.model';
import {
  Category,
  CoreCompetency,
  ExpertiseLevel,
  SectionHeading,
  Stat,
  Technology,
} from './skills-page.model';

const YEARS_OF_EXPERIENCE = 8;

export const PAGE_HEADER_CONTENT: PageHeaderContent = {
  label: '// SKILLS',
  title: `Everything I build with`,
  description1: `Over the past ${YEARS_OF_EXPERIENCE}+ years, I've worked with a wide range of technologies to build production-grade software 
  across multiple industries.`,
  description2: `These are the tools I've relied on to design, develop, test, and deploy enterprise applications.`,
};

export const TECHNOLOGIES: Technology[] = [
  {
    id: 1,
    name: 'Angular',
    icon: 'diAngularOriginal',
    rating: 5,
    years: 8,
    categories: [Category.Framework, Category.Frontend],
    hasPlusYears: true,
  },
  {
    id: 2,
    name: 'TypeScript',
    icon: 'diTypescriptOriginal',
    rating: 5,
    years: 8,
    categories: [Category.Language, Category.Frontend],
    hasPlusYears: true,
  },
  {
    id: 3,
    name: 'JavaScript',
    icon: 'diJavascriptOriginal',
    rating: 5,
    years: 8,
    categories: [Category.Language, Category.Frontend],
    hasPlusYears: true,
  },
  {
    id: 4,
    name: 'RxJS',
    icon: 'diRxjsOriginal',
    rating: 4,
    years: 8,
    categories: [Category.Frontend],
    hasPlusYears: true,
  },
  {
    id: 5,
    name: 'HTML',
    icon: 'diHtml5Original',
    rating: 5,
    years: 8,
    categories: [Category.Frontend],
    hasPlusYears: true,
  },
  {
    id: 6,
    name: 'CSS',
    icon: 'diCss3Original',
    rating: 5,
    years: 8,
    categories: [Category.Frontend],
    hasPlusYears: true,
  },
  {
    id: 7,
    name: 'Spring Boot',
    icon: 'diSpringOriginal',
    rating: 4,
    years: 5,
    categories: [Category.Framework, Category.Backend],
    hasPlusYears: true,
  },
  {
    id: 8,
    name: 'Java',
    icon: 'diJavaOriginal',
    rating: 4,
    years: 5,
    categories: [Category.Language, Category.Backend],
    hasPlusYears: true,
  },
  {
    id: 9,
    name: 'REST APIs',
    icon: 'tablerCodeDots',
    rating: 4,
    years: 8,
    categories: [Category.Frontend, Category.Backend],
    hasPlusYears: true,
  },
  {
    id: 10,
    name: 'Swagger (OpenAPI)',
    icon: 'diOpenapiOriginal',
    rating: 4,
    years: 5,
    categories: [Category.Tools, Category.Backend],
    hasPlusYears: true,
  },
  {
    id: 11,
    name: 'PostgreSQL',
    icon: 'diPostgresqlOriginal',
    rating: 3,
    years: 5,
    categories: [Category.Database, Category.Backend],
    hasPlusYears: true,
  },
  {
    id: 12,
    name: 'Claude Code',
    icon: 'logo/claude-code.png',
    rating: 3,
    years: 0.5,
    categories: [Category.AI, Category.Tools],
    hasPlusYears: false,
  },
  {
    id: 13,
    name: 'Git',
    icon: 'diGitOriginal',
    rating: 4,
    years: 8,
    categories: [Category.Tools],
    hasPlusYears: true,
  },
  {
    id: 14,
    name: 'Jasmine',
    icon: 'diJasmineOriginal',
    rating: 4,
    years: 5,
    categories: [Category.Testing, Category.Frontend],
    hasPlusYears: true,
  },
  {
    id: 15,
    name: 'JUnit',
    icon: 'diJunitOriginalWordmark',
    rating: 3,
    years: 5,
    categories: [Category.Testing, Category.Backend],
    hasPlusYears: true,
  },
  {
    id: 16,
    name: 'Tailwind CSS',
    icon: 'diTailwindcssOriginal',
    rating: 4,
    years: 2,
    categories: [Category.Frontend],
    hasPlusYears: true,
  },
  {
    id: 17,
    name: 'Bootstrap',
    icon: 'diBootstrapOriginal',
    rating: 4,
    years: 3,
    categories: [Category.Frontend],
    hasPlusYears: false,
  },
  {
    id: 18,
    name: 'GitHub',
    icon: 'diGithubOriginal',
    rating: 4,
    years: 6,
    categories: [Category.Tools],
    hasPlusYears: true,
  },
  {
    id: 19,
    name: 'GitHub Actions',
    icon: 'diGithubactionsOriginal',
    rating: 2,
    years: 2,
    categories: [Category.DevOps],
    hasPlusYears: false,
  },
  {
    id: 20,
    name: 'GitHub Pages',
    icon: 'tablerBrandGithub',
    rating: 2,
    years: 1,
    categories: [Category.DevOps],
    hasPlusYears: true,
  },
  {
    id: 21,
    name: 'Bitbucket',
    icon: 'diBitbucketOriginal',
    rating: 4,
    years: 2,
    categories: [Category.Tools],
    hasPlusYears: false,
  },
  {
    id: 22,
    name: 'Bamboo',
    icon: 'diBambooOriginal',
    rating: 2,
    years: 1,
    categories: [Category.DevOps],
    hasPlusYears: true,
  },
  {
    id: 23,
    name: 'ArgoCD',
    icon: 'diArgocdOriginal',
    rating: 2,
    years: 1,
    categories: [Category.DevOps],
    hasPlusYears: true,
  },
  {
    id: 24,
    name: 'MySQL',
    icon: 'diMysqlOriginal',
    rating: 3,
    years: 2,
    categories: [Category.Database, Category.Backend],
    hasPlusYears: true,
  },
  {
    id: 25,
    name: 'React',
    icon: 'diReactOriginal',
    rating: 2,
    years: 1,
    categories: [Category.Framework, Category.Frontend],
    hasPlusYears: false,
  },
  {
    id: 26,
    name: 'Microsoft Copilot',
    icon: 'logo/microsoft-copilot.png',
    rating: 3,
    years: 1,
    categories: [Category.AI, Category.Tools],
    hasPlusYears: true,
  },
  {
    id: 27,
    name: 'Java EE',
    icon: 'diJavaOriginal',
    rating: 2,
    years: 0.5,
    categories: [Category.Framework, Category.Backend],
    hasPlusYears: false,
  },
  {
    id: 28,
    name: 'JSP',
    icon: 'diJavaPlain',
    rating: 2,
    years: 0.5,
    categories: [Category.Backend, Category.Frontend],
    hasPlusYears: false,
  },
  {
    id: 29,
    name: 'Express.js',
    icon: 'diExpressOriginal',
    rating: 2,
    years: 0.5,
    categories: [Category.Framework, Category.Backend],
    hasPlusYears: false,
  },
  {
    id: 30,
    name: 'Salesforce LWC',
    icon: 'diSalesforceOriginal',
    rating: 2,
    years: 0.5,
    categories: [Category.LowCode, Category.Frontend],
    hasPlusYears: false,
  },
  {
    id: 31,
    name: 'Salesforce Apex',
    icon: 'diSalesforceOriginal',
    rating: 2,
    years: 0.5,
    categories: [Category.LowCode, Category.Backend],
    hasPlusYears: false,
  },
];

export const CORE_COMPETENCIES: CoreCompetency[] = [
  {
    id: 1,
    name: 'Enterprise Frontend Development',
    icon: 'tablerDeviceDesktopCode',
    description: `Designed, developed, and maintained enterprise Angular applications 
    that support complex business workflows, delivering scalable, maintainable, 
    and user-focused solutions across multiple industries.`,
  },
  {
    id: 2,
    name: 'Full-stack Development',
    icon: 'tablerStack2',
    description: `Developed end-to-end application features across the frontend and backend, 
    implementing business logic, integrating databases, and delivering production-ready solutions 
    throughout the full software development lifecycle.`,
  },
  {
    id: 3,
    name: 'Angular Modernization',
    icon: 'tablerRocket',
    description: `Modernized legacy Angular applications by upgrading framework versions, 
    improving project architecture, reducing technical debt, introducing automated testing, 
    and establishing a stronger foundation for long-term maintainability.`,
  },
  {
    id: 4,
    name: 'Frontend Testing & Quality Engineering',
    icon: 'tablerShieldCheck',
    description: `Improved application quality by writing unit tests with Jasmine, 
    increasing automated test coverage, debugging production issues, and contributing 
    to reliable frontend development workflows.`,
  },
  {
    id: 5,
    name: 'Technical Leadership & Collaboration',
    icon: 'tablerBulb',
    description: `Served as the frontend subject matter expert by providing technical guidance, 
    performing code reviews, conducting stakeholder demonstrations, 
    and collaborating with cross-functional Agile teams to deliver high-quality solutions.`,
  },
  {
    id: 6,
    name: 'API Design & Integration',
    icon: 'tablerCodeDots',
    description: `Designed, implemented, documented, and consumed RESTful APIs using Spring Boot and 
    OpenAPI, enabling reliable communication between frontend applications and backend services 
    while supporting scalable system integration.`,
  },
];

export const STATISTICS: Stat[] = [
  {
    value: `${YEARS_OF_EXPERIENCE}+`,
    field: 'Years of\nExperience',
    icon: 'tablerCalendarCode',
  },
  {
    value: `${TECHNOLOGIES.length}`,
    field: 'Technologies\nUsed',
    icon: 'tablerCode',
  },
  {
    value: `12`,
    field: 'Production\nApplications',
    icon: 'tablerServerBolt',
  },
];

export const EXPERTISE_LEVEL: ExpertiseLevel = {
  description:
    'Expertise levels are self-assessed based on hands-on experience in production projects.',
  levels: [
    {
      rating: 5,
      name: 'Expert',
    },
    {
      rating: 4,
      name: 'Advanced',
    },
    {
      rating: 3,
      name: 'Proficient',
    },
    {
      rating: 2,
      name: 'Familiar',
    },
  ],
};

export const TECHNOLOGIES_SECTION_HEADER: SectionHeading = {
  title: 'Technologies',
  description: 'Browse by category',
};

export const CORE_COMPETENCIES_SECTION_HEADER: SectionHeading = {
  title: 'Core Competencies',
  description: 'The strengths I bring to enterprise software projects.',
};
